[package]
    edition = "2024"
    name    = "shmemcam"
    version = "0.1.0"

[dependencies]
nokhwa = { version = "0.10.7", default-features = false, features = ["input-msmf", "output-threaded", "camera-sync-impl"] }
windows-service = "0.8.0"
winmmf = "0.3.0"
